import type { ChatThread, Message, Order, Service, Transaction } from "./types";

export const mockServices: Service[] = [
  {
    id: "svc-1",
    title: "Complete Shopify store setup with theme customization",
    titleAr: "إعداد متجر شوبيفاي متكامل مع تخصيص القالب",
    category: "shopify",
    description:
      "I will set up your Shopify store from scratch — install a premium theme, configure payments, shipping, taxes, and add up to 30 products with optimized SEO.",
    descriptionAr:
      "أقوم بإعداد متجر شوبيفاي من الصفر — تركيب قالب احترافي، إعداد الدفع والشحن والضرائب، وإضافة حتى 30 منتجاً مع تحسين السيو.",
    cover: "shopify",
    rating: 4.9,
    reviewCount: 184,
    ordersInQueue: 5,
    freelancerId: "user-2",
    freelancerName: "Layla Mansour",
    packages: [
      {
        tier: "basic",
        name: "Starter",
        price: 450,
        deliveryDays: 3,
        revisions: 1,
        features: ["Theme install", "10 products", "Payment setup"],
      },
      {
        tier: "standard",
        name: "Growth",
        price: 950,
        deliveryDays: 5,
        revisions: 3,
        features: [
          "Premium theme",
          "Up to 30 products",
          "Shipping zones",
          "Email setup",
          "Basic SEO",
        ],
      },
      {
        tier: "premium",
        name: "Pro",
        price: 1850,
        deliveryDays: 7,
        revisions: 5,
        features: [
          "Custom theme tweaks",
          "50 products",
          "Apps integration",
          "Advanced SEO",
          "Speed optimization",
          "30-day support",
        ],
      },
    ],
    tags: ["Shopify", "E-commerce", "Setup"],
  },
  {
    id: "svc-2",
    title: "High-converting Meta & TikTok ads campaign",
    titleAr: "حملة إعلانات ميتا وتيك توك عالية التحويل",
    category: "ads",
    description:
      "Launch and manage profitable paid ad campaigns across Meta and TikTok with custom creatives, audience research, and weekly optimization.",
    descriptionAr:
      "إطلاق وإدارة حملات إعلانية مربحة على ميتا وتيك توك مع تصاميم مخصصة وأبحاث الجمهور وتحسين أسبوعي.",
    cover: "marketing",
    rating: 4.8,
    reviewCount: 96,
    ordersInQueue: 3,
    freelancerId: "user-3",
    freelancerName: "Omar Khalid",
    packages: [
      {
        tier: "basic",
        name: "Single Channel",
        price: 600,
        deliveryDays: 4,
        revisions: 2,
        features: ["1 platform", "3 ad creatives", "Audience research"],
      },
      {
        tier: "standard",
        name: "Dual Channel",
        price: 1250,
        deliveryDays: 6,
        revisions: 4,
        features: [
          "2 platforms",
          "6 ad creatives",
          "Pixel setup",
          "A/B testing",
        ],
      },
      {
        tier: "premium",
        name: "Full Funnel",
        price: 2400,
        deliveryDays: 10,
        revisions: 6,
        features: [
          "All platforms",
          "12 creatives",
          "Retargeting",
          "Weekly reports",
          "30-day management",
        ],
      },
    ],
    tags: ["Meta", "TikTok", "Performance"],
  },
  {
    id: "svc-3",
    title: "Modern brand identity and logo design",
    titleAr: "هوية بصرية وشعار احترافي",
    category: "branding",
    description:
      "Distinctive, modern brand identity package — logo, color system, typography, and brand guidelines built around your business.",
    descriptionAr:
      "هوية بصرية مميزة وعصرية — شعار ونظام ألوان وخطوط ودليل هوية كامل مصمم خصيصاً لعملك.",
    cover: "branding",
    rating: 5.0,
    reviewCount: 212,
    ordersInQueue: 2,
    freelancerId: "user-4",
    freelancerName: "Yasmin Al-Harbi",
    packages: [
      {
        tier: "basic",
        name: "Logo only",
        price: 350,
        deliveryDays: 2,
        revisions: 2,
        features: ["1 logo concept", "PNG + SVG", "1 round of revisions"],
      },
      {
        tier: "standard",
        name: "Brand Mini",
        price: 850,
        deliveryDays: 5,
        revisions: 4,
        features: [
          "3 logo concepts",
          "Color palette",
          "Typography",
          "Source files",
        ],
      },
      {
        tier: "premium",
        name: "Brand Identity",
        price: 1900,
        deliveryDays: 10,
        revisions: 6,
        features: [
          "Logo system",
          "Brand guidelines PDF",
          "Social templates",
          "Business cards",
          "All source files",
        ],
      },
    ],
    tags: ["Branding", "Logo", "Identity"],
  },
  {
    id: "svc-4",
    title: "On-page SEO audit and optimization",
    titleAr: "تدقيق وتحسين السيو الداخلي للمتجر",
    category: "seo",
    description:
      "Full on-page SEO audit and optimization for your store — meta tags, schema, internal linking, and content recommendations to grow organic traffic.",
    descriptionAr:
      "تدقيق سيو شامل وتحسين متجرك — وسوم الميتا، البيانات المنظمة، الروابط الداخلية، وتوصيات المحتوى.",
    cover: "marketing",
    rating: 4.7,
    reviewCount: 67,
    ordersInQueue: 1,
    freelancerId: "user-5",
    freelancerName: "Khaled Saeed",
    packages: [
      {
        tier: "basic",
        name: "Audit",
        price: 280,
        deliveryDays: 3,
        revisions: 1,
        features: ["20-page audit", "Action plan"],
      },
      {
        tier: "standard",
        name: "Optimization",
        price: 720,
        deliveryDays: 7,
        revisions: 2,
        features: [
          "Audit",
          "Meta optimization",
          "Schema markup",
          "Speed report",
        ],
      },
      {
        tier: "premium",
        name: "Growth Plan",
        price: 1500,
        deliveryDays: 14,
        revisions: 4,
        features: [
          "Full audit",
          "Optimization",
          "Content plan",
          "30-day monitoring",
        ],
      },
    ],
    tags: ["SEO", "Organic", "Audit"],
  },
  {
    id: "svc-5",
    title: "Salla store launch with 360 setup",
    titleAr: "إطلاق متجر سلة مع إعداد شامل",
    category: "salla",
    description:
      "Launch your Salla store fast — domain, payments, shipping, theme customization, and product catalog setup tailored to the Saudi market.",
    descriptionAr:
      "أطلق متجرك على سلة بسرعة — الدومين، الدفع، الشحن، تخصيص القالب، وكتالوج المنتجات بما يلائم السوق السعودي.",
    cover: "shopify",
    rating: 4.9,
    reviewCount: 142,
    ordersInQueue: 4,
    freelancerId: "user-2",
    freelancerName: "Layla Mansour",
    packages: [
      {
        tier: "basic",
        name: "Quick launch",
        price: 500,
        deliveryDays: 3,
        revisions: 1,
        features: ["Domain", "Theme", "10 products"],
      },
      {
        tier: "standard",
        name: "Full setup",
        price: 1100,
        deliveryDays: 6,
        revisions: 3,
        features: [
          "Custom theme",
          "30 products",
          "Payment & shipping",
          "Tax setup",
        ],
      },
      {
        tier: "premium",
        name: "Launch + Marketing",
        price: 2200,
        deliveryDays: 10,
        revisions: 5,
        features: [
          "Full setup",
          "50 products",
          "Marketing kit",
          "Launch campaign",
        ],
      },
    ],
    tags: ["Salla", "E-commerce", "Saudi"],
  },
  {
    id: "svc-6",
    title: "Product photography for e-commerce stores",
    titleAr: "تصوير منتجات احترافي للمتاجر الإلكترونية",
    category: "photography",
    description:
      "Studio-quality product photos with white background and lifestyle shots — perfect for your store, ads, and social media.",
    descriptionAr:
      "صور منتجات بجودة استوديو على خلفية بيضاء ولقطات حياة عملية — مثالية لمتجرك وإعلاناتك ومواقع التواصل.",
    cover: "branding",
    rating: 4.9,
    reviewCount: 88,
    ordersInQueue: 2,
    freelancerId: "user-6",
    freelancerName: "Noura Al-Sabah",
    packages: [
      {
        tier: "basic",
        name: "5 products",
        price: 400,
        deliveryDays: 4,
        revisions: 1,
        features: ["5 products", "White background", "3 angles each"],
      },
      {
        tier: "standard",
        name: "15 products",
        price: 1000,
        deliveryDays: 6,
        revisions: 2,
        features: ["15 products", "White + lifestyle", "5 angles each"],
      },
      {
        tier: "premium",
        name: "30 products",
        price: 1900,
        deliveryDays: 10,
        revisions: 3,
        features: [
          "30 products",
          "Studio + lifestyle",
          "Retouching",
          "Social crops",
        ],
      },
    ],
    tags: ["Photography", "Product", "Studio"],
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-1",
    serviceId: "svc-2",
    serviceTitle: "High-converting Meta & TikTok ads campaign",
    serviceCover: "marketing",
    packageTier: "standard",
    price: 1250,
    clientId: "user-1",
    clientName: "Sara Ahmed",
    freelancerId: "user-3",
    freelancerName: "Omar Khalid",
    status: "in_progress",
    progress: 60,
    createdAt: Date.now() - 1000 * 60 * 60 * 48,
    dueAt: Date.now() + 1000 * 60 * 60 * 72,
    notes: "Targeting Saudi market, focus on women 25-40.",
  },
  {
    id: "ord-2",
    serviceId: "svc-3",
    serviceTitle: "Modern brand identity and logo design",
    serviceCover: "branding",
    packageTier: "premium",
    price: 1900,
    clientId: "user-1",
    clientName: "Sara Ahmed",
    freelancerId: "user-4",
    freelancerName: "Yasmin Al-Harbi",
    status: "review",
    progress: 85,
    createdAt: Date.now() - 1000 * 60 * 60 * 96,
    dueAt: Date.now() + 1000 * 60 * 60 * 24,
  },
  {
    id: "ord-3",
    serviceId: "svc-1",
    serviceTitle: "Complete Shopify store setup with theme customization",
    serviceCover: "shopify",
    packageTier: "basic",
    price: 450,
    clientId: "user-1",
    clientName: "Sara Ahmed",
    freelancerId: "user-2",
    freelancerName: "Layla Mansour",
    status: "completed",
    progress: 100,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    dueAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
  },
];

export const mockChats: ChatThread[] = [
  {
    id: "thr-1",
    participantId: "user-3",
    participantName: "Omar Khalid",
    lastMessage: "I will share the first creatives by tomorrow.",
    lastMessageAt: Date.now() - 1000 * 60 * 18,
    unreadCount: 2,
    online: true,
  },
  {
    id: "thr-2",
    participantId: "user-4",
    participantName: "Yasmin Al-Harbi",
    lastMessage: "The brand guidelines are ready for review.",
    lastMessageAt: Date.now() - 1000 * 60 * 60 * 3,
    unreadCount: 0,
    online: false,
  },
  {
    id: "thr-3",
    participantId: "user-2",
    participantName: "Layla Mansour",
    lastMessage: "Thanks! Glad you loved the new store.",
    lastMessageAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    unreadCount: 0,
    online: true,
  },
];

export const mockMessages: Record<string, Message[]> = {
  "thr-1": [
    {
      id: "m1",
      threadId: "thr-1",
      senderId: "user-3",
      text: "Hi Sara, thanks for ordering. I'll start the audience research now.",
      createdAt: Date.now() - 1000 * 60 * 60 * 4,
    },
    {
      id: "m2",
      threadId: "thr-1",
      senderId: "me",
      text: "Great! Looking forward to it.",
      createdAt: Date.now() - 1000 * 60 * 60 * 3,
    },
    {
      id: "m3",
      threadId: "thr-1",
      senderId: "user-3",
      text: "I'll target women 25-40 in major Saudi cities, focused on lifestyle.",
      createdAt: Date.now() - 1000 * 60 * 60 * 2,
    },
    {
      id: "m4",
      threadId: "thr-1",
      senderId: "me",
      text: "Perfect. Add men 30-45 too if budget allows.",
      createdAt: Date.now() - 1000 * 60 * 30,
    },
    {
      id: "m5",
      threadId: "thr-1",
      senderId: "user-3",
      text: "I will share the first creatives by tomorrow.",
      createdAt: Date.now() - 1000 * 60 * 18,
    },
  ],
  "thr-2": [
    {
      id: "m1",
      threadId: "thr-2",
      senderId: "user-4",
      text: "The brand guidelines are ready for review.",
      createdAt: Date.now() - 1000 * 60 * 60 * 3,
    },
  ],
  "thr-3": [
    {
      id: "m1",
      threadId: "thr-3",
      senderId: "me",
      text: "The store looks amazing, thank you!",
      createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2 - 1000 * 60 * 30,
    },
    {
      id: "m2",
      threadId: "thr-3",
      senderId: "user-2",
      text: "Thanks! Glad you loved the new store.",
      createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    },
  ],
};

export const mockTransactions: Transaction[] = [
  {
    id: "tx-1",
    type: "earning",
    amount: 1250,
    description: "Meta & TikTok ads — Sara Ahmed",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    status: "completed",
  },
  {
    id: "tx-2",
    type: "earning",
    amount: 850,
    description: "Brand mini — Mohammad Z.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    status: "completed",
  },
  {
    id: "tx-3",
    type: "withdrawal",
    amount: -1500,
    description: "Withdrawal to bank ****4521",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    status: "completed",
  },
  {
    id: "tx-4",
    type: "earning",
    amount: 720,
    description: "SEO optimization — Hatim S.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    status: "pending",
  },
  {
    id: "tx-5",
    type: "earning",
    amount: 1900,
    description: "Brand identity — Khalid R.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    status: "completed",
  },
];
