[[pages]]
path = "/"
screenshotTimestamp = "2026-04-27T10:58:57Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/02866450-0395-4c21-8e25-10d4db145e8b/da825794-ace4-4e79-9947-53b65cc27734/mPmk05D"

[[pages]]
path = "/dashboard"
screenshotTimestamp = "2026-04-26T17:43:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/4eb05fb0-d0f4-416b-8ccb-129c410a84a6/3bc38025-d610-42a1-94fe-84dd43e27b72/AlaC6Hu"

[[pages]]
path = "/service-edit/new"
screenshotTimestamp = "2026-04-26T17:43:14Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/4eb05fb0-d0f4-416b-8ccb-129c410a84a6/3bc38025-d610-42a1-94fe-84dd43e27b72/MsIqofO"
