// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/freelance-mobile/Auth.tsx": () => import("../components/mockups/freelance-mobile/Auth.tsx"),
  "./components/mockups/freelance-mobile/Categories.tsx": () => import("../components/mockups/freelance-mobile/Categories.tsx"),
  "./components/mockups/freelance-mobile/Chat.tsx": () => import("../components/mockups/freelance-mobile/Chat.tsx"),
  "./components/mockups/freelance-mobile/Dashboard.tsx": () => import("../components/mockups/freelance-mobile/Dashboard.tsx"),
  "./components/mockups/freelance-mobile/Home.tsx": () => import("../components/mockups/freelance-mobile/Home.tsx"),
  "./components/mockups/freelance-mobile/Onboarding.tsx": () => import("../components/mockups/freelance-mobile/Onboarding.tsx"),
  "./components/mockups/freelance-mobile/Orders.tsx": () => import("../components/mockups/freelance-mobile/Orders.tsx"),
  "./components/mockups/freelance-mobile/ServiceDetails.tsx": () => import("../components/mockups/freelance-mobile/ServiceDetails.tsx"),
  "./components/mockups/freelance-mobile/Wallet.tsx": () => import("../components/mockups/freelance-mobile/Wallet.tsx")
};
